name: validate

on:
  workflow_call:
    inputs:
      config:
        description: Argument(s) to renovate-config-validator
        required: false
        type: string
      runs-on:
        description: Job runs-on
        required: false
        type: string
        default: ubuntu-latest

jobs:
  validate:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: |
          set -eux -o pipefail
          echo "$script" > renovate-config-validator.sh
          chmod +x renovate-config-validator.sh
        env:
          script: |
            #!/bin/bash
            set -eux -o pipefail
            cd /workspace
            exec renovate-config-validator ${{ inputs.config }}
      - uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker-cmd-file: renovate-config-validator.sh
          docker-volumes: ${{ github.workspace }}:/workspace
